@startuml

!include <C4/C4_Context.puml>
!include <C4/C4_Container.puml>
!include <C4/C4_Component.puml>

Person(back_office_user, "Сотрудник бэк-офиса")
Person(call_center_user, "Сотрудник call-центра")
Container_Boundary(abs, "Автоматизированная банковская система"){
    Component(abs_bets, "Подсистема ставок")
    Component(absDb, "База данных системы АБС")
}
Container(site, "Сайт", "React.js, PHP")

System_Boundary(crm, "Call-центр и системы работы с клиентами"){
    Container(crmCallCenter, "CRM", "React.js, Java Spring Boot, PostgreSQL")
    System_Ext(partnerCallCenter, "Партнерский call-центр")
}
Container(sftp_server, "Сервер обмена данными")
Container(internetBankMololith, "Интернет-банк", "ASP.NET MVC 4.5, MS SQL")
Container(eventProcessor, "Ивент процессор", "Apache Kafka")

Rel(back_office_user, abs_bets, "Вносит данные процентных ставок")
Rel(abs_bets, absDb, "SQL")
Rel(abs_bets, eventProcessor, "Публикует процентные ставки в топик bets.created")
Rel(eventProcessor, site, "Читает события из топика bets.created")
Rel(eventProcessor, crm, "Читает события из топика bets.created")
Rel(eventProcessor, internetBankMololith, "Читает события из топика bets.created")

Rel(call_center_user, sftp_server, "XLS-файл со ставками")
Rel(sftp_server, partnerCallCenter, "XLS-файл со ставками")

@enduml
